# Generated by Django 3.2 on 2021-04-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
