# Generated by Django 3.2 on 2021-04-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='size',
            field=models.CharField(default='is-medium', max_length=50),
        ),
    ]
