# Generated by Django 3.2 on 2021-04-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
