# Generated by Django 3.2 on 2021-04-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210419_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='urls',
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='urlDescription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('work-exp', 'work experience'), ('home', 'home'), ('about-me', 'about me'), ('projects', 'projects')], max_length=200),
        ),
    ]
