# Generated by Django 3.2 on 2021-04-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210419_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='size',
            field=models.CharField(choices=[('is-large', 'large padding'), ('is-medium', 'medium padding'), ('is-small', 'small padding')], default='is-medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('work-exp', 'work experience'), ('projects', 'projects'), ('about-me', 'about me'), ('home', 'home')], max_length=200),
        ),
    ]
