# Generated by Django 3.2 on 2021-04-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210419_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='size',
            field=models.CharField(choices=[('is-medium', 'medium padding'), ('is-large', 'large padding'), ('is-small', 'small padding')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('work-exp', 'work experience'), ('home', 'home'), ('about-me', 'about me'), ('projects', 'projects')], max_length=200),
        ),
    ]
