# Generated by Django 3.2 on 2021-04-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210419_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='size',
            field=models.CharField(choices=[('is-small', 'small padding'), ('is-large', 'large padding'), ('is-medium', 'medium padding')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('work-exp', 'work experience'), ('home', 'home'), ('projects', 'projects'), ('about-me', 'about me')], max_length=200),
        ),
    ]
