# Generated by Django 3.2 on 2021-04-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210419_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='backgroundImageUrl',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='size',
            field=models.CharField(choices=[('is-large', 'large padding'), ('is-small', 'small padding'), ('is-medium', 'medium padding')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('projects', 'projects'), ('home', 'home'), ('work-exp', 'work experience'), ('contact', 'contact'), ('about-me', 'about me')], max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
