# Generated by Django 3.2 on 2021-04-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210423_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='size',
            field=models.CharField(choices=[('is-medium', 'medium padding'), ('is-large', 'large padding'), ('is-small', 'small padding')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('projects', 'projects'), ('home', 'home'), ('about-me', 'about me'), ('hidden', 'hidden'), ('work-exp', 'work experience'), ('contact', 'contact')], max_length=200),
        ),
    ]
